version: '3'
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
